spring:
  application:
    name: mspokemon

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://diogo123:diogo123@localhost:27017/ms-pokemon?authSource=admin

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#CLIENT
pokeapi:
  url: https://pokeapi.co/api/v2/
  glitch: https://pokeapi.glitch.me/v1/

stoneapi:
  url: https://pokeapi.glitch.me/v1/
#QUEUES
mq:
  queues:
    ms_pokemon: ms-pokemon