server:
  port: 0

spring:
  application:
    name: mspokemon

  #JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    #Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stones
    username: postgres
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://diogo123:diogo123@localhost:27017/ms-pokemon?authSource=admin

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

pokeapi:
  url: https://pokeapi.co/api/v2/
  glitch: https://pokeapi.glitch.me/v1/

stoneapi:
  url: https://pokeapi.glitch.me/v1/