server:
  port: 0

spring:
  application:
    name: msattack
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  #Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-attack
    username: postgres
    password: 123456

#EUREKA -SERVICE DISCOVERY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}