version: '3'

services:
  postgres:
    image: postgres
    container_name: ms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  mongo:
    image: mongo
    container_name: ms-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: diogo123
      MONGO_INITDB_ROOT_PASSWORD: diogo123
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  mongo-compose-network:
    driver: bridge
  postgres-network:
    driver: bridge