version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: diogo123
      MONGO_INITDB_ROOT_PASSWORD: diogo123
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
  postgres-network:
    driver: bridge